name: Deploy Node Application
on:
 push:
    branches:
      - main

jobs: 
 build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t akashprasad123/ProCo_Backend .
      - name: Publish Image to Docker Hub
        run: docker push akashprasad123/ProCo_Backend:latest
 deploy:
    needs: build 
    runs-on: self-hosted 
    steps: 
      - name: Pull image from Docker Hub
        run: docker pull akashprasad123/ProCo_Backend:latest
      - name: Delete old container
        run: docker rm -f backend-container  
      - name: Run Docker Container
        run: |
          docker run -d -p 3005:3005 --name backend-container \
          -e CONNECTION_STRING='${{ secrets.MONGO_URL }}' \ 
          -e MY_SECRET='${{ secrets.MY_SECRET }}' \
          -e NODE_ENV='${{ secrets.NODE_ENV }}' \
          -e S3_REGION='${{ secrets.S3_REGION }}' \
          -e S3_BUCKET_NAME='${{ secrets.S3_BUCKET_NAME }}' \
          -e S3_ACCESS_KEY='${{ secrets.S3_ACCESS_KEY }}' \
          -e S3_SECRET_KEY='${{ secrets.S3_SECRET_KEY }}' \
          -e HOST='${{ secrets.HOST }}' \
          -e SERVICE='${{ secrets.SERVICE }}' \
          -e EMAIL_PORT='${{ secrets.EMAIL_PORT }}' \
          -e SECURE='${{ secrets.SECURE }}' \
          -e USER='${{ secrets.USER }}' \
          -e PASS='${{ secrets.PASS }}' \
          akashprasad123/ProCo_Backend:latest

