name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: action/checkout@v4
      - name: Login to docket hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t akashprasad123/nodejs-app  .
      - name: Publish Image to docker hub
        run: docker push akashprasad123/nodejs-app:latest

  deploy:
   needs: build
   runs-on: self-hosted
   steps:
     - name: Pull image from docker hub
       run: docker pull akashprasad123/nodejs-app:latest
     - name: Run Docker Container
       run: docker run -d -p 3005:3005 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' akashprasad123/nodejs-app
