name: Deploy Node Application
on:
 push:
    branches:
      - main

jobs: 
 build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t akashprasad123/proco .
      - name: Publish Image to Docker Hub
        run: docker push akashprasad123/proco:latest
 deploy:
    needs: build 
    runs-on: self-hosted 
    steps: 
      - name: Cleanup old images
        run: |
         docker image prune -f
         docker rmi $(docker images -f "dangling=true" -q) || true
      - name: Pull image from Docker Hub
        run: docker pull akashprasad123/proco:latest
      - name: Delete old container  
        run: docker rm -f proco-container  
      - name: Run Docker Container
        run: |
         docker run -d -p 3005:3005 --name proco-container \
            -e CONNECTION_STRING='${{ secrets.CONNECTION_STRING }}' \
            -e MY_SECRET='${{ secrets.MY_SECRET }}' \
            -e NODE_ENV='${{ secrets.NODE_ENV }}' \
            -e S3_REGION='${{ secrets.S3_REGION }}' \
            -e S3_BUCKET_NAME='${{ secrets.S3_BUCKET_NAME }}' \
            -e S3_ACCESS_KEY='${{ secrets.S3_ACCESS_KEY }}' \
            -e S3_SECRET_KEY='${{ secrets.S3_SECRET_KEY }}' \
            -e HOST='${{ secrets.HOST }}' \
            -e SERVICE='${{ secrets.SERVICE }}' \
            -e EMAIL_PORT='${{ secrets.EMAIL_PORT }}' \
            -e SECURE='${{ secrets.SECURE }}' \
            -e USER='${{ secrets.USER }}' \
            -e PASS='${{ secrets.PASS }}' \
            akashprasad123/proco:latest


